"""
Django settings for billflow project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import sys
from datetime import timedelta
from utils.paths import get_project_root, get_apps_dir
from decouple import config
from .logging import LOGGING

# Defines the project's root directory and adds the "apps" subdirectory  
# to Python's module search path 
BASE_DIR = get_project_root()
sys.path.insert(0, str(get_apps_dir()))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
     # Local apps
    "users.apps.UsersConfig",
    "authentication.apps.AuthenticationConfig",
    "notifications.apps.NotificationsConfig",
    "wallets.apps.WalletsConfig",
    "payments.apps.PaymentsConfig",
    "subscriptions.apps.SubscriptionsConfig",
   
    # Django core apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    # Third party apps
    'django_celery_beat',
    'channels',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt.token_blacklist',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'dj_rest_auth',
    'dj_rest_auth.registration',
    'drf_spectacular',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'billflow.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'billflow.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('POSTGRES_DB'),
        'USER': config('POSTGRES_USER'),
        'PASSWORD': config('POSTGRES_PASSWORD'),
        'HOST': config('POSTGRES_HOST'),
        'PORT': config('POSTGRES_PORT', cast=int),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',
        'user': '1000/day',
    },
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'EXCEPTION_HANDLER': 'api_response.exceptions.custom_exception_handler',
}

# SimpleJWT
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": config("REDIS_URL"),
        "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
    }
}

CELERY_BROKER_URL = config("REDIS_URL")
CELERY_RESULT_BACKEND = config("REDIS_URL")
CELERY_TASK_QUEUES_DEFAULT = 'default'

CELERY_TASK_ROUTES = {
    'payments.tasks.process_webhook_event': {'queue': 'webhooks'},
    'payments.tasks.send_payment_success_notification': {'queue': 'notifications'},
    'payments.tasks.send_payment_failed_notification': {'queue': 'notifications'},
    'notifications.tasks.send_email_task': {'queue': 'notifications'},
}

# task message is only removed from the queue after
# the task completes. If the worker crashes mid-task, the message goes back
# to the queue and another worker picks it up
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True

CELERY_BEAT_SCHEDULE = {
    'reconcile-unprocessed-webhooks': {
        'task': 'payments.tasks.reconcile_unprocessed_webhooks',
        'schedule': 60,  # every 1 minute (temporary for testing)
    },
    'dispatch-subscription-expiries': {
        'task': 'subscriptions.dispatch_expiries',
        'schedule': 600.0,  # 10 minutes in seconds
    },
}

ASGI_APPLICATION = 'billflow.asgi.application'


AUTH_USER_MODEL = 'users.User'

# allauth needs this to know which site it's running on
# SITE_ID=1 is the default site created by Django's sites framework
SITE_ID = 1

# Tell allauth to use email as the primary identifier, not username
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'

# dj-rest-auth config
REST_AUTH = {
    'USE_JWT': True, # Use JWT instead of token auth
    'JWT_AUTH_HTTPONLY': False,  # send refresh token in response body, not httponly cookie
    'TOKEN_MODEL': None,  # disable DRF's default token model since we're using JWT
    'PASSWORD_RESET_CONFIRM_SERIALIZER': 'authentication.serializers.CustomPasswordResetConfirmSerializer',
}

# allauth social account config
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': config('GOOGLE_CLIENT_ID'),
            'secret': config('GOOGLE_CLIENT_SECRET'),
            'key': '',
        },
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'VERIFIED_EMAIL': True, # Only allow verified Google emails
    }
}

PASSWORD_RESET_CONFIRM_URL = config('PASSWORD_RESET_CONFIRM_URL')

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# billflow/settings.py
SPECTACULAR_SETTINGS = {
    'TITLE': 'BillFlow API',
    'DESCRIPTION': (
        'A multi-tenant bill payment, wallet and subscription API. '
        'Built with Django REST Framework, Paystack, Stripe, and Django Channels.'
    ),
    'VERSION': '1.0.0',
    'CONTACT': {
        'name': 'GitHub Repository',
        'url': 'https://github.com/hengage/billflow',
    },
    'SERVE_INCLUDE_SCHEMA': False,  # hides the raw schema endpoint from the Swagger UI itself
    # JWT auth button in Swagger UI — lets you paste a token and authenticate
    'SECURITY': [{'BearerAuth': []}],
    'COMPONENTS': {
        'securitySchemes': {
            'BearerAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
            }
        }
    },
    # Explicit enum naming to prevent collision warnings
    'ENUM_NAME_OVERRIDES': {
        'PaymentProviderEnum': 'payments.constants.PaymentProvider',
    },
}

# Payment Provider API Keys
PAYSTACK_SECRET_KEY = config('PAYSTACK_SECRET_KEY')
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY')