# Generated by Django 5.2.11 on 2026-04-07 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_plan_options_remove_plan_billing_cycle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='price_ngn',
        ),
    ]
