# Generated by Django 5.2.11 on 2026-04-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_remove_plan_price_ngn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('renewed', 'Renewed')], default='active', max_length=20),
        ),
    ]
