# Generated by Django 5.2.11 on 2026-04-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_renewal_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='renewal_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
