# Generated by Django 5.2.11 on 2026-04-22 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outbox',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('domain', models.CharField(db_index=True, max_length=50)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Outbox Entry',
                'verbose_name_plural': 'Outbox Entries',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['domain', 'status', 'id'], name='infra_outbo_domain_5bb3cd_idx'), models.Index(fields=['status', 'created_at'], name='infra_outbo_status_ea93d0_idx')],
            },
        ),
    ]
