# Generated by Django 5.2.11 on 2026-04-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outbox',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('drained', 'Drained'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
