# Generated by Django 5.2.11 on 2026-04-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0002_alter_outbox_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='outbox',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='outbox',
            index=models.Index(fields=['status', 'updated_at'], name='infra_outbo_status_709d64_idx'),
        ),
    ]
