# Generated by Django 5.2.11 on 2026-04-01 01:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('request_path', models.CharField(max_length=255)),
                ('recovery_point', models.CharField(choices=[('started', 'Started'), ('payment_created', 'Payment Created'), ('provider_initialized', 'Provider Initialized'), ('finished', 'Finished')], default='started', max_length=50)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('request_params', models.JSONField()),
                ('response_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('NGN', 'Nigerian Naira'), ('USD', 'US Dollar')], default='NGN', max_length=3)),
                ('provider', models.CharField(choices=[('paystack', 'Paystack'), ('stripe', 'Stripe')], max_length=20)),
                ('purpose', models.CharField(choices=[('wallet_topup', 'Wallet Top-up'), ('subscription', 'Subscription Payment')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='payments.idempotencykey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='idempotencykey',
            index=models.Index(fields=['user', 'key', 'request_path'], name='payments_id_user_id_5fa83f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='idempotencykey',
            unique_together={('user', 'key', 'request_path')},
        ),
    ]
