# Generated by Django 5.2.11 on 2026-04-04 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_webhooklog_payment_card_brand_payment_last_four_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooklog',
            name='failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='permanently_failed',
            field=models.BooleanField(default=False),
        ),
    ]
