# Generated by Django 5.2.11 on 2026-04-11 03:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_webhooklog_failure_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='idempotencykey',
            name='recovery_point',
            field=models.CharField(choices=[('started', 'Started'), ('payment_created', 'Payment Created'), ('finished', 'Finished')], default='started', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('wallet_topup', 'Wallet Top-up'), ('subscription', 'New Subscription'), ('renew_subscription', 'Subscription Renewal')], max_length=50),
        ),
        migrations.CreateModel(
            name='StoredPaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('paystack', 'Paystack'), ('stripe', 'Stripe')], max_length=20)),
                ('authorization_code', models.CharField(blank=True, max_length=100)),
                ('provider_customer_id', models.CharField(blank=True, max_length=100)),
                ('billing_email', models.CharField(blank=True, max_length=255)),
                ('signature', models.CharField(blank=True, max_length=100)),
                ('last_four', models.CharField(max_length=4)),
                ('card_brand', models.CharField(max_length=20)),
                ('exp_month', models.CharField(max_length=2)),
                ('exp_year', models.CharField(max_length=4)),
                ('bank', models.CharField(blank=True, max_length=100)),
                ('card_type', models.CharField(blank=True, max_length=50)),
                ('is_reusable', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stored_payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('provider', 'paystack')), fields=('user', 'signature'), name='unique_paystack_card_per_user'), models.UniqueConstraint(condition=models.Q(('provider', 'stripe')), fields=('user', 'authorization_code'), name='unique_stripe_method_per_user')],
            },
        ),
    ]
