# Generated by Django 5.2.11 on 2026-04-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_idempotencykey_recovery_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooklog',
            name='reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('wallet_topup', 'Wallet Top-up'), ('subscription', 'New Subscription'), ('renew_subscription', 'Subscription Renewal'), ('switch_plan', 'Plan Switch')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['reference', 'received_at'], name='payments_we_referen_b65ebe_idx'),
        ),
    ]
