# Generated by Django 5.2.11 on 2026-04-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_webhooklog_reference_alter_payment_purpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='failure_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
