# Generated by Django 5.2.11 on 2026-04-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_payment_failure_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('stripe', 'Stripe'), ('wallet', 'Wallet')], max_length=20),
        ),
        migrations.AlterField(
            model_name='storedpaymentmethod',
            name='provider',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('stripe', 'Stripe'), ('wallet', 'Wallet')], max_length=20),
        ),
        migrations.AlterField(
            model_name='webhooklog',
            name='provider',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('stripe', 'Stripe'), ('wallet', 'Wallet')], max_length=20),
        ),
    ]
