# Generated by Django 5.2.11 on 2026-03-14 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('wallet_topup', 'Wallet Top Up'), ('subscription_expiring', 'Subscription Expiring'), ('subscription_expired', 'Subscription Expired'), ('subscription_activated', 'Subscription Activated')], max_length=50),
        ),
        migrations.CreateModel(
            name='UserNotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payments_email', models.BooleanField(default=True)),
                ('payments_push', models.BooleanField(default=True)),
                ('subscriptions_email', models.BooleanField(default=True)),
                ('subscriptions_push', models.BooleanField(default=True)),
                ('wallet_email', models.BooleanField(default=True)),
                ('wallet_push', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences_obj', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
