# Generated by Django 5.2.11 on 2026-04-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type_usernotificationpreferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('wallet_topup', 'Wallet Top Up'), ('subscription_expiring', 'Subscription Expiring'), ('subscription_expired', 'Subscription Expired'), ('subscription_activated', 'Subscription Activated'), ('subscription_renewed', 'Subscription Renewed'), ('renewal_failed', 'Renewal Failed')], max_length=50),
        ),
    ]
