# Generated by Django 5.2.11 on 2026-04-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('wallet_topup', 'Wallet Top Up'), ('subscription_expiring', 'Subscription Expiring'), ('subscription_expired', 'Subscription Expired'), ('subscription_activated', 'Subscription Activated'), ('subscription_renewed', 'Subscription Renewed'), ('subscription_cancelled', 'Subscription Cancelled'), ('renewal_failed', 'Renewal Failed'), ('plan_switched', 'Plan Switched'), ('welcome', 'Welcome')], max_length=50),
        ),
    ]
